version: 2
jobs:
  build:
    docker:
      - image: golang:1.11
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -u
      - run: go test -v ./test/integration/...

