version: 2
jobs:
  build:
    docker:
      - image: golang:1.13
    steps:
      - checkout
      - run: go get -u
      - run: make test

  deploy:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t hekike/outlier-istio:latest .
          docker tag hekike/outlier-istio:latest hekike/outlier-istio:${CIRCLE_TAG}
          docker push hekike/outlier-istio:${CIRCLE_TAG}
          docker push hekike/outlier-istio:latest

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
