apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: outlier-istio
  namespace: istio-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: outlier-istio
    spec:
      containers:
      - name: outlier-istio
        image: hekike/outlier-istio:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
